#!/usr/bin/env bash
set -uo pipefail

VERSION="2026-05-19-routeros-chr-installer-r7"

INSTALL_CMD="/usr/local/sbin/routerosinstall"
CONSOLE_CMD="/usr/local/sbin/routeros"
CONFIG_DIR="/etc/routerosinstall"
CONFIG_FILE="$CONFIG_DIR/config.env"
PRESET_RSC="$CONFIG_DIR/routeros-preset.rsc"
LIB_DIR="/usr/local/lib/routerosinstall"
HOSTNET_SCRIPT="$LIB_DIR/hostnet.sh"
START_SCRIPT="$LIB_DIR/start-vm.sh"
SERVICE_FILE="/etc/systemd/system/routeros-chr.service"
ROLLBACK_SCRIPT="$CONFIG_DIR/last-hostnet-rollback.sh"
NM_UNMANAGED_CONF="/etc/NetworkManager/conf.d/99-routerosinstall-unmanaged.conf"
NETWORKD_PREFIX="/etc/systemd/network/00-routerosinstall"
NETWORKD_LEGACY_PREFIX="/etc/systemd/network/80-routerosinstall"

RED=$'\033[31m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
BLUE=$'\033[34m'
BOLD=$'\033[1m'
RESET=$'\033[0m'

ok(){ printf '%s\n' "${GREEN}[完成]${RESET} $*" >&2; }
info(){ printf '%s\n' "${BLUE}[信息]${RESET} $*" >&2; }
warn(){ printf '%s\n' "${YELLOW}[提醒]${RESET} $*" >&2; }
err(){ printf '%s\n' "${RED}[错误]${RESET} $*" >&2; }
has_cmd(){ command -v "$1" >/dev/null 2>&1; }

pause(){
  printf '%s' "按回车继续..." >&2
  IFS= read -r _ || true
}

need_root(){
  if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    err "请使用 root 执行：sudo bash 9.sh 或 sudo routerosinstall"
    exit 1
  fi
}

read_default(){
  local prompt="$1" def="${2:-}" val
  if [ -n "$def" ]; then
    printf '%s' "$prompt [$def]: " >&2
  else
    printf '%s' "$prompt: " >&2
  fi
  IFS= read -r val || true
  printf '%s' "${val:-$def}"
}

confirm(){
  local prompt="$1" def="${2:-y}" val hint
  if [ "$def" = "y" ]; then
    hint="Y/n"
  else
    hint="y/N"
  fi
  printf '%s' "$prompt [$hint]: " >&2
  IFS= read -r val || true
  val="${val:-$def}"
  case "${val,,}" in
    y|yes|1|true|ok|是|好|确认) return 0 ;;
    *) return 1 ;;
  esac
}

space_to_continue(){
  local key
  printf '%s' "按空格继续执行，按其他任意键取消: " >&2
  IFS= read -rsn1 key || true
  printf '\n' >&2
  [ "$key" = " " ]
}

print_title(){
  clear 2>/dev/null || true
  printf '%s\n' "${BOLD}RouterOS CHR KVM 安装与管理脚本${RESET}"
  printf '%s\n' "版本: $VERSION"
  printf '%s\n\n' "配置目录: $CONFIG_DIR"
}

quote_env(){
  printf '%q' "$1"
}

atomic_write(){
  local target="$1" mode="${2:-0644}" dir tmp
  dir="$(dirname "$target")"
  mkdir -p "$dir"
  tmp="$(mktemp "$dir/.routerosinstall.XXXXXX")" || return 1
  if ! cat > "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  chmod "$mode" "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$target"
}

is_uint(){
  [[ "${1:-}" =~ ^[0-9]+$ ]]
}

is_ifname(){
  [[ "${1:-}" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]]
}

is_ros_ifname(){
  [[ "${1:-}" =~ ^[A-Za-z0-9_.:-]{1,63}$ ]]
}

is_mac(){
  [[ "${1:-}" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]
}

is_ipv4(){
  local IFS=. a b c d extra oct
  [[ "${1:-}" =~ ^[0-9]+(\.[0-9]+){3}$ ]] || return 1
  read -r a b c d extra <<< "$1"
  [ -z "${extra:-}" ] || return 1
  for oct in "$a" "$b" "$c" "$d"; do
    is_uint "$oct" || return 1
    [ "$((10#$oct))" -ge 0 ] && [ "$((10#$oct))" -le 255 ] || return 1
  done
}

is_prefix(){
  is_uint "${1:-}" && [ "$1" -ge 0 ] && [ "$1" -le 32 ]
}

is_size_value(){
  [[ "${1:-}" =~ ^[0-9]+([KkMmGgTtPp])?$ ]]
}

trim(){
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

strip_spaces(){
  local s="$1"
  s="${s//[[:space:]]/}"
  printf '%s' "$s"
}

normalize_uint(){
  local label="$1" value="$2" def="$3" min="$4" max="${5:-}"
  if ! is_uint "$value"; then
    warn "$label 不是有效数字，已恢复为 $def"
    value="$def"
  fi
  if [ "$value" -lt "$min" ]; then
    warn "$label 不能小于 $min，已调整。"
    value="$min"
  fi
  if [ -n "$max" ] && [ "$value" -gt "$max" ]; then
    warn "$label 不能大于 $max，已调整。"
    value="$max"
  fi
  printf '%s' "$value"
}

validate_name_list(){
  local label="$1" checker="$2" list="$3" item ok=0
  for item in $list; do
    if ! "$checker" "$item"; then
      err "$label 包含非法名称: $item"
      ok=1
    fi
  done
  return "$ok"
}

management_ifaces(){
  {
    ip route show default 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="dev") print $(i+1)}'
    if [ -n "${SSH_CONNECTION:-}" ]; then
      local remote="${SSH_CONNECTION%% *}"
      ip route get "$remote" 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="dev") print $(i+1)}'
    fi
  } | awk 'NF && !seen[$0]++'
}

iface_is_management(){
  local iface="$1" mgmt
  while IFS= read -r mgmt; do
    [ "$iface" = "$mgmt" ] && return 0
  done < <(management_ifaces)
  return 1
}

iface_has_host_network(){
  local iface="$1"
  ip -o addr show dev "$iface" 2>/dev/null | grep -q . && return 0
  ip route show dev "$iface" 2>/dev/null | grep -q . && return 0
  return 1
}

write_host_rollback_script(){
  local script="${1:-$ROLLBACK_SCRIPT}" iface addr route
  mkdir -p "$CONFIG_DIR"
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' 'set -u'
    printf '# Generated by routerosinstall at %s\n' "$(date -Is 2>/dev/null || date)"
    for iface in $VM_IFACES; do
      [ -n "$iface" ] || continue
      [ "$iface" = "none" ] && continue
      ip link show "$iface" >/dev/null 2>&1 || continue
      printf 'ip link set %q nomaster 2>/dev/null || true\n' "$iface"
      printf 'ip link set %q up 2>/dev/null || true\n' "$iface"
      while IFS= read -r addr; do
        [ -n "$addr" ] || continue
        printf 'ip addr add %q dev %q 2>/dev/null || true\n' "$addr" "$iface"
      done < <(ip -o addr show dev "$iface" 2>/dev/null | awk '{print $4}')
      while IFS= read -r route; do
        [ -n "$route" ] || continue
        printf 'ip route replace %s 2>/dev/null || true\n' "$route"
      done < <(ip route show dev "$iface" 2>/dev/null)
    done
  } | atomic_write "$script" 0700
}

confirm_host_iface_takeover(){
  local dangerous=() iface answer
  for iface in $VM_IFACES; do
    [ -n "$iface" ] || continue
    [ "$iface" = "none" ] && continue
    if ! is_ifname "$iface"; then
      err "宿主机网口名称非法: $iface"
      return 1
    fi
    if ! ip link show "$iface" >/dev/null 2>&1; then
      warn "宿主机网口不存在，启动时会跳过: $iface"
      continue
    fi
    if iface_is_management "$iface" || iface_has_host_network "$iface"; then
      dangerous+=("$iface")
    fi
  done

  if [ "${#dangerous[@]}" -eq 0 ]; then
    ALLOW_DANGEROUS_IFACES=""
    return 0
  fi

  printf '\n'
  warn "以下网口当前带有宿主机地址/路由，或看起来是管理入口: ${dangerous[*]}"
  warn "RouterOS 启动时会清空这些网口 IP 并加入 br-rosX，SSH 可能断开。"
  write_host_rollback_script "$ROLLBACK_SCRIPT" || true
  info "已生成尽力回滚脚本: $ROLLBACK_SCRIPT"
  answer="$(read_default "如果确认仍要接管，请输入 YES" "")"
  if [ "$answer" != "YES" ]; then
    err "已取消网口接管配置。"
    return 1
  fi
  ALLOW_DANGEROUS_IFACES="${dangerous[*]}"
}

qemu_img_format_probe(){
  local path="$1" timeout_s="${2:-3}" actual
  has_cmd qemu-img || return 1
  has_cmd timeout || return 1
  [ -f "$path" ] || return 1

  if ! actual="$(timeout "$timeout_s" qemu-img info "$path" 2>/dev/null | awk -F': ' '/^file format:/ {print $2; exit}')"; then
    return 1
  fi
  case "$actual" in
    raw|qcow2|vdi|vmdk) printf '%s' "$actual"; return 0 ;;
  esac
  return 1
}

detect_disk_format(){
  local path="$1" guessed actual
  guessed="$(guess_disk_format "$path")"
  case "${path,,}" in
    *.img|*.raw) printf '%s' "$guessed"; return 0 ;;
  esac
  if actual="$(qemu_img_format_probe "$path" 3)"; then
    printf '%s' "$actual"
    return 0
  fi
  printf '%s' "$guessed"
}

validate_vm_config(){
  local ok_flag=0 count_if count_br count_tap count_mac item cpu_count
  VM_CPUS="$(normalize_uint "vCPU 数量" "$VM_CPUS" "$(nproc 2>/dev/null || echo 4)" 1 256)"
  VM_MEMORY_MB="$(normalize_uint "内存 MB" "$VM_MEMORY_MB" "1024" 128 262144)"
  NET_QUEUES="$(normalize_uint "virtio-net 队列数" "$NET_QUEUES" "1" 1 16)"
  cpu_count="$(nproc 2>/dev/null || echo 0)"
  if is_uint "$cpu_count" && [ "$cpu_count" -gt 0 ] && [ "$VM_CPUS" -gt "$cpu_count" ]; then
    warn "vCPU 数量大于宿主机逻辑 CPU 数，QEMU 可以超分，但不建议生产长期这样跑。"
  fi
  case "${DISK_FORMAT,,}" in
    raw|qcow2|vdi|vmdk) DISK_FORMAT="${DISK_FORMAT,,}" ;;
    *) warn "未知镜像格式 $DISK_FORMAT，已按 raw 处理。"; DISK_FORMAT="raw" ;;
  esac
  case "${HOST_NET_MODE:-}" in
    runtime|networkd|nm-unmanaged|both) ;;
    *)
      if [ "${PERSIST_HOST_NET:-1}" = "1" ]; then
        HOST_NET_MODE="networkd"
      else
        HOST_NET_MODE="runtime"
      fi
      ;;
  esac
  case "${HOST_NET_MODE:-}" in
    runtime) PERSIST_HOST_NET="0" ;;
    *) PERSIST_HOST_NET="1" ;;
  esac

  count_if="$(wc -w <<< "${VM_IFACES:-}")"
  count_br="$(wc -w <<< "${VM_BRIDGES:-}")"
  count_tap="$(wc -w <<< "${VM_TAPS:-}")"
  count_mac="$(wc -w <<< "${VM_MACS:-}")"
  if [ "$count_if" -lt 1 ] || [ "$count_if" -ne "$count_br" ] || [ "$count_if" -ne "$count_tap" ] || [ "$count_if" -ne "$count_mac" ]; then
    err "VM_IFACES/VM_BRIDGES/VM_TAPS/VM_MACS 数量不一致。"
    ok_flag=1
  fi
  for item in $VM_IFACES; do
    [ "$item" = "none" ] && continue
    is_ifname "$item" || { err "宿主机网口名称非法: $item"; ok_flag=1; }
  done
  validate_name_list "桥名称" is_ifname "$VM_BRIDGES" || ok_flag=1
  validate_name_list "tap 名称" is_ifname "$VM_TAPS" || ok_flag=1
  for item in $VM_MACS; do
    is_mac "$item" || { err "MAC 地址非法: $item"; ok_flag=1; }
  done
  [ "$ok_flag" -eq 0 ]
}

validate_routeros_config(){
  local ok_flag=0 dns dns_trim start_int end_int lan_net start_net end_net _dns_list
  [ -n "${ROS_IDENTITY:-}" ] || { err "RouterOS identity 不能为空。"; ok_flag=1; }
  is_ros_ifname "$ROS_WAN_IFACE" || { err "WAN 口名称非法: $ROS_WAN_IFACE"; ok_flag=1; }
  is_ros_ifname "$ROS_LAN_BRIDGE" || { err "LAN bridge 名称非法: $ROS_LAN_BRIDGE"; ok_flag=1; }
  validate_name_list "LAN 口列表" is_ros_ifname "$ROS_LAN_PORTS" || ok_flag=1
  is_ipv4 "$ROS_LAN_IP" || { err "LAN IP 非法: $ROS_LAN_IP"; ok_flag=1; }
  is_prefix "$ROS_LAN_PREFIX" || { err "LAN 掩码前缀非法: $ROS_LAN_PREFIX"; ok_flag=1; }
  is_ipv4 "$ROS_DHCP_START" || { err "DHCP 起始地址非法: $ROS_DHCP_START"; ok_flag=1; }
  is_ipv4 "$ROS_DHCP_END" || { err "DHCP 结束地址非法: $ROS_DHCP_END"; ok_flag=1; }
  IFS=',' read -r -a _dns_list <<< "$ROS_DNS_SERVERS"
  for dns in "${_dns_list[@]}"; do
    dns_trim="$(trim "$dns")"
    is_ipv4 "$dns_trim" || { err "DNS 地址非法: $dns_trim"; ok_flag=1; }
  done
  if [ "$ok_flag" -eq 0 ]; then
    start_int="$(ip_to_int "$ROS_DHCP_START")"
    end_int="$(ip_to_int "$ROS_DHCP_END")"
    if [ "$start_int" -gt "$end_int" ]; then
      err "DHCP 起始地址不能大于结束地址。"
      ok_flag=1
    fi
    lan_net="$(cidr_network "$ROS_LAN_IP" "$ROS_LAN_PREFIX")"
    start_net="$(cidr_network "$ROS_DHCP_START" "$ROS_LAN_PREFIX")"
    end_net="$(cidr_network "$ROS_DHCP_END" "$ROS_LAN_PREFIX")"
    if [ "$lan_net" != "$start_net" ] || [ "$lan_net" != "$end_net" ]; then
      warn "DHCP 地址池不在 LAN 网段 $lan_net/$ROS_LAN_PREFIX 内。"
    fi
  fi
  [ "$ok_flag" -eq 0 ]
}

save_config(){
  mkdir -p "$CONFIG_DIR"
  {
    printf 'IMAGE_PATH=%q\n' "$IMAGE_PATH"
    printf 'DISK_FORMAT=%q\n' "$DISK_FORMAT"
    printf 'QEMU_BIN=%q\n' "$QEMU_BIN"
    printf 'VM_CPUS=%q\n' "$VM_CPUS"
    printf 'VM_MEMORY_MB=%q\n' "$VM_MEMORY_MB"
    printf 'NET_QUEUES=%q\n' "$NET_QUEUES"
    printf 'VM_IFACES=%q\n' "$VM_IFACES"
    printf 'VM_BRIDGES=%q\n' "$VM_BRIDGES"
    printf 'VM_TAPS=%q\n' "$VM_TAPS"
    printf 'VM_MACS=%q\n' "$VM_MACS"
    printf 'PERSIST_HOST_NET=%q\n' "$PERSIST_HOST_NET"
    printf 'HOST_NET_MODE=%q\n' "$HOST_NET_MODE"
    printf 'ALLOW_DANGEROUS_IFACES=%q\n' "$ALLOW_DANGEROUS_IFACES"
    printf 'SERIAL_SOCK=%q\n' "$SERIAL_SOCK"
    printf 'MONITOR_SOCK=%q\n' "$MONITOR_SOCK"
    printf 'PID_FILE=%q\n' "$PID_FILE"
    printf 'ROS_IDENTITY=%q\n' "$ROS_IDENTITY"
    printf 'ROS_WAN_IFACE=%q\n' "$ROS_WAN_IFACE"
    printf 'ROS_LAN_BRIDGE=%q\n' "$ROS_LAN_BRIDGE"
    printf 'ROS_LAN_PORTS=%q\n' "$ROS_LAN_PORTS"
    printf 'ROS_LAN_IP=%q\n' "$ROS_LAN_IP"
    printf 'ROS_LAN_PREFIX=%q\n' "$ROS_LAN_PREFIX"
    printf 'ROS_DHCP_START=%q\n' "$ROS_DHCP_START"
    printf 'ROS_DHCP_END=%q\n' "$ROS_DHCP_END"
    printf 'ROS_DNS_SERVERS=%q\n' "$ROS_DNS_SERVERS"
  } | atomic_write "$CONFIG_FILE" 0600
}

load_config(){
  IMAGE_PATH="/root/routeros.img"
  DISK_FORMAT="raw"
  QEMU_BIN="qemu-system-aarch64"
  VM_CPUS="$(nproc 2>/dev/null || echo 4)"
  VM_MEMORY_MB="1024"
  NET_QUEUES="4"
  VM_IFACES="eth1 eth2 eth3"
  VM_BRIDGES="br-ros1 br-ros2 br-ros3"
  VM_TAPS="tap-ros1 tap-ros2 tap-ros3"
  VM_MACS="52:54:00:21:00:01 52:54:00:21:00:02 52:54:00:21:00:03"
  PERSIST_HOST_NET="1"
  HOST_NET_MODE=""
  ALLOW_DANGEROUS_IFACES=""
  SERIAL_SOCK="/run/routeros/serial.sock"
  MONITOR_SOCK="/run/routeros/monitor.sock"
  PID_FILE="/run/routeros/routeros-chr.pid"
  ROS_IDENTITY="CHR-R2"
  ROS_WAN_IFACE="ether1"
  ROS_LAN_BRIDGE="br-lan"
  ROS_LAN_PORTS="ether2 ether3"
  ROS_LAN_IP="10.10.10.1"
  ROS_LAN_PREFIX="24"
  ROS_DHCP_START="10.10.10.100"
  ROS_DHCP_END="10.10.10.200"
  ROS_DNS_SERVERS="223.5.5.5,119.29.29.29"

  if [ -r "$CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    . "$CONFIG_FILE"
  fi
  if [ -z "${HOST_NET_MODE:-}" ]; then
    if [ "${PERSIST_HOST_NET:-1}" = "1" ]; then
      HOST_NET_MODE="networkd"
    else
      HOST_NET_MODE="runtime"
    fi
  fi
}

bootstrap_install(){
  need_root
  local src
  src="$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null || printf '%s' "$0")"
  if [ ! -f "$src" ]; then
    err "无法定位当前脚本文件，请把 9.sh 保存到本地后再执行。"
    exit 1
  fi
  mkdir -p "$(dirname "$INSTALL_CMD")"
  install -m 0755 "$src" "$INSTALL_CMD"
  ok "已生成命令: $INSTALL_CMD"
  info "现在输入 routerosinstall 即可进入菜单。"
  info "后续启动虚拟机后，输入 routeros 可进入 RouterOS 控制台。"
}

pkg_installed(){
  dpkg -s "$1" >/dev/null 2>&1
}

find_aarch64_efi_firmware(){
  local fw
  for fw in \
    /usr/share/qemu-efi-aarch64/QEMU_EFI.fd \
    /usr/share/AAVMF/AAVMF_CODE.fd \
    /usr/share/AAVMF/AAVMF_CODE.no-secboot.fd; do
    [ -r "$fw" ] && { printf '%s\n' "$fw"; return 0; }
  done
  return 1
}

dependency_report(){
  local arch kernel virt kvm_state vhost_state qemu_state efi_fw efi_state
  arch="$(uname -m)"
  kernel="$(uname -r)"
  virt="未知"
  if grep -q -E 'Features.*(virt|hyp)' /proc/cpuinfo 2>/dev/null; then
    virt="CPU 信息包含虚拟化特征"
  elif [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then
    virt="ARM64 平台，实际以 /dev/kvm 为准"
  fi

  if [ -e /dev/kvm ]; then
    kvm_state="可用"
  else
    kvm_state="未发现 /dev/kvm"
  fi
  if [ -e /dev/vhost-net ]; then
    vhost_state="可用"
  else
    vhost_state="未发现 /dev/vhost-net，virtio-net 会退回普通 tap"
  fi
  if has_cmd "$QEMU_BIN"; then
    qemu_state="$("$QEMU_BIN" --version 2>/dev/null | head -n1)"
  elif has_cmd qemu-system-aarch64; then
    qemu_state="$(qemu-system-aarch64 --version 2>/dev/null | head -n1)"
  else
    qemu_state="未安装 qemu-system-aarch64"
  fi

  printf '%s\n' "系统架构: $arch"
  printf '%s\n' "内核版本: $kernel"
  printf '%s\n' "虚拟化: $virt"
  printf '%s\n' "KVM: $kvm_state"
  printf '%s\n' "vhost-net: $vhost_state"
  printf '%s\n' "QEMU: $qemu_state"
  if [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then
    if efi_fw="$(find_aarch64_efi_firmware)"; then
      efi_state="$efi_fw"
    else
      efi_state="missing qemu-efi-aarch64; RouterOS ARM64 EFI image will not boot"
    fi
    printf '%s\n' "AArch64 UEFI: $efi_state"
  fi
  printf '%s\n' "systemd: $(has_cmd systemctl && systemctl --version | head -n1 || echo 未发现)"
  printf '\n'

  local item cmd pkg status
  printf '%s\n' "依赖检查:"
  while IFS='|' read -r cmd pkg; do
    [ -n "$cmd" ] || continue
    if has_cmd "$cmd"; then
      status="${GREEN}OK${RESET}"
    else
      status="${YELLOW}缺失，包名通常为 $pkg${RESET}"
    fi
    printf '  %-22s %b\n' "$cmd" "$status"
  done <<'EOF_DEPS'
qemu-system-aarch64|qemu-system-arm
qemu-img|qemu-utils
timeout|coreutils
ip|iproute2
socat|socat
ssh|openssh-client
unzip|unzip
curl|curl
ethtool|ethtool
lsmod|kmod
modprobe|kmod
systemctl|systemd
EOF_DEPS
}

install_dependencies(){
  local packages missing pkg
  packages=(
    qemu-system-arm
    qemu-utils
    coreutils
    iproute2
    socat
    openssh-client
    unzip
    curl
    ethtool
    kmod
    procps
  )
  case "$(uname -m)" in
    aarch64|arm64) packages+=(qemu-efi-aarch64) ;;
  esac
  missing=()
  for pkg in "${packages[@]}"; do
    pkg_installed "$pkg" || missing+=("$pkg")
  done

  if [ "${#missing[@]}" -eq 0 ]; then
    ok "APT 依赖包已安装。"
  else
    warn "将安装缺失包: ${missing[*]}"
    DEBIAN_FRONTEND=noninteractive apt-get update || return 1
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${missing[@]}" || return 1
    ok "依赖安装完成。"
  fi

  modprobe kvm 2>/dev/null || true
  modprobe vhost_net 2>/dev/null || true
}

menu_dependencies(){
  print_title
  dependency_report
  printf '\n'
  if space_to_continue; then
    install_dependencies
  else
    warn "已取消依赖安装。"
  fi
  pause
}

physical_ifaces(){
  local p ifname type
  for p in /sys/class/net/*; do
    [ -e "$p" ] || continue
    ifname="${p##*/}"
    [ "$ifname" = "lo" ] && continue
    case "$ifname" in
      br-*|docker*|veth*|tap*|tun*|wg*|virbr*|ifb*|bond*|dummy*) continue ;;
    esac
    type="$(cat "$p/type" 2>/dev/null || echo 0)"
    [ "$type" = "1" ] || continue
    printf '%s\n' "$ifname"
  done
}

detect_network_managers(){
  local found=0
  printf '%s\n' "网络管理器检测:"
  if systemctl is-active --quiet systemd-networkd 2>/dev/null; then
    printf '  %-24s %s\n' "systemd-networkd" "运行中"
    found=1
  else
    printf '  %-24s %s\n' "systemd-networkd" "未运行"
  fi
  if systemctl is-active --quiet NetworkManager 2>/dev/null; then
    printf '  %-24s %s\n' "NetworkManager" "运行中"
    found=1
  else
    printf '  %-24s %s\n' "NetworkManager" "未运行"
  fi
  if systemctl is-active --quiet networking 2>/dev/null; then
    printf '  %-24s %s\n' "ifupdown/networking" "运行中"
    found=1
  fi
  if systemctl is-active --quiet connman 2>/dev/null; then
    printf '  %-24s %s\n' "connman" "运行中"
    found=1
  fi
  if [ -d /etc/netplan ]; then
    printf '  %-24s %s\n' "netplan" "存在 /etc/netplan"
  fi
  [ "$found" -eq 0 ] && warn "没有发现常见网络管理服务处于运行状态。"
}

show_iface_usage(){
  local iface="$1" master addrs routes config
  master="$(basename "$(readlink -f "/sys/class/net/$iface/master" 2>/dev/null)" 2>/dev/null || true)"
  addrs="$(ip -o -4 addr show dev "$iface" 2>/dev/null | awk '{print $4}' | xargs 2>/dev/null || true)"
  routes="$(ip route show dev "$iface" 2>/dev/null | sed 's/^/    /')"
  config="$(grep -Rsl "Name=$iface\\|interface-name=$iface\\|$iface" /etc/systemd/network /etc/netplan /etc/network/interfaces /etc/NetworkManager/system-connections 2>/dev/null | head -n5 | xargs 2>/dev/null || true)"
  printf '  %-10s state=%-8s master=%-10s addr=%s\n' "$iface" "$(cat "/sys/class/net/$iface/operstate" 2>/dev/null)" "${master:-无}" "${addrs:-无}"
  if [ -n "$routes" ]; then
    printf '%s\n' "$routes"
  fi
  if [ -n "$config" ]; then
    printf '    可能相关配置: %s\n' "$config"
  fi
}

menu_network_check(){
  print_title
  detect_network_managers
  printf '\n%s\n' "链路概览:"
  ip -br link show 2>/dev/null || true
  printf '\n%s\n' "地址概览:"
  ip -br addr show 2>/dev/null || true
  printf '\n%s\n' "默认路由:"
  ip route show default 2>/dev/null || true
  printf '\n%s\n' "物理网口占用情况:"
  local iface
  while IFS= read -r iface; do
    show_iface_usage "$iface"
  done < <(physical_ifaces)
  printf '\n'
  warn "后续选择给 RouterOS 的宿主机网口会被 bridge/tap 接管，脚本启动虚拟机时会清空这些网口上的 IP 并加入对应 br-rosX。"
  warn "不要把当前 SSH 管理入口选进去，除非你有串口、HDMI 或其他备用管理通道。"
  warn "如果 NetworkManager、netplan 或 systemd-networkd 已经管理这些网口，需要按菜单 3 的持久化选项处理，避免重启后被系统重新抢占。"
  pause
}

guess_disk_format(){
  case "${1,,}" in
    *.qcow2) printf '%s' "qcow2" ;;
    *.vdi) printf '%s' "vdi" ;;
    *.vmdk) printf '%s' "vmdk" ;;
    *) printf '%s' "raw" ;;
  esac
}

disk_ext_for_format(){
  case "${1,,}" in
    qcow2) printf '%s' "qcow2" ;;
    vdi) printf '%s' "vdi" ;;
    vmdk) printf '%s' "vmdk" ;;
    *) printf '%s' "img" ;;
  esac
}

extract_zip_image(){
  local zipfile="$1" entry="$2" entry_format out tmp raw_tmp ext
  entry_format="$(guess_disk_format "$entry")"

  if [ "$entry_format" != "raw" ] && has_cmd qemu-img; then
    out="/root/routeros.img"
    if [ -f "$out" ] && ! confirm "$out 已存在，是否覆盖" "n"; then
      warn "已取消解压转换。"
      return 1
    fi
    tmp="$(mktemp "/root/.routerosinstall-${entry_format}.XXXXXX")" || return 1
    raw_tmp="$(mktemp "/root/.routerosinstall-raw.XXXXXX")" || { rm -f "$tmp"; return 1; }
    info "正在从 $zipfile 解压 $entry"
    if ! unzip -p "$zipfile" "$entry" > "$tmp"; then
      rm -f "$tmp" "$raw_tmp"
      return 1
    fi
    info "正在把 $entry_format 转换为 raw: $out"
    rm -f "$raw_tmp"
    if ! qemu-img convert -f "$entry_format" -O raw "$tmp" "$raw_tmp"; then
      rm -f "$tmp" "$raw_tmp"
      return 1
    fi
    chmod 0600 "$raw_tmp" 2>/dev/null || true
    mv -f "$raw_tmp" "$out"
    rm -f "$tmp"
    IMAGE_PATH="$out"
    DISK_FORMAT="raw"
    return 0
  fi

  ext="$(disk_ext_for_format "$entry_format")"
  out="/root/routeros.$ext"
  if [ -f "$out" ] && ! confirm "$out 已存在，是否覆盖" "n"; then
    warn "已取消解压。"
    return 1
  fi
  tmp="$(mktemp "/root/.routerosinstall-image.XXXXXX")" || return 1
  info "正在从 $zipfile 解压 $entry 到 $out"
  if ! unzip -p "$zipfile" "$entry" > "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  chmod 0600 "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$out"
  IMAGE_PATH="$out"
  DISK_FORMAT="$(detect_disk_format "$IMAGE_PATH")"
}

choose_image_from_root(){
  local default="/root/routeros.img"
  local -a files
  local i sel chosen entry
  files=()

  if [ -f "$default" ]; then
    ok "检测到 $default"
    IMAGE_PATH="$default"
    DISK_FORMAT="$(detect_disk_format "$IMAGE_PATH")"
    return 0
  fi

  while IFS= read -r f; do
    files+=("$f")
  done < <(find /root -maxdepth 1 -type f \( -iname '*.img' -o -iname '*.raw' -o -iname '*.qcow2' -o -iname '*.vdi' -o -iname '*.vmdk' -o -iname '*.img.zip' -o -iname '*.vdi.zip' -o -iname '*.zip' \) 2>/dev/null | sort)

  if [ "${#files[@]}" -eq 0 ]; then
    warn "/root 下没有找到 routeros.img 或其他 img/zip 镜像。"
    IMAGE_PATH="$(read_default "请输入 RouterOS 镜像完整路径" "$IMAGE_PATH")"
    DISK_FORMAT="$(guess_disk_format "$IMAGE_PATH")"
    return 0
  fi

  printf '%s\n' "没有找到 /root/routeros.img，但发现以下镜像候选:"
  for i in "${!files[@]}"; do
    printf '  %s. %s\n' "$((i+1))" "${files[$i]}"
  done
  printf '%s' "选择要使用的镜像编号，直接回车手动输入路径: "
  IFS= read -r sel || true
  if [ -z "$sel" ]; then
    IMAGE_PATH="$(read_default "请输入 RouterOS 镜像完整路径" "$IMAGE_PATH")"
    DISK_FORMAT="$(detect_disk_format "$IMAGE_PATH")"
    return 0
  fi
  if ! [[ "$sel" =~ ^[0-9]+$ ]] || [ "$sel" -lt 1 ] || [ "$sel" -gt "${#files[@]}" ]; then
    warn "选择无效，保持当前路径: $IMAGE_PATH"
    return 1
  fi

  chosen="${files[$((sel-1))]}"
  case "${chosen,,}" in
    *.zip)
      if ! has_cmd unzip; then
        err "缺少 unzip，先执行菜单 1 安装依赖。"
        return 1
      fi
      entry="$(unzip -Z1 "$chosen" 2>/dev/null | grep -Ei '\.(img|raw|qcow2|vdi|vmdk)$' | head -n1 || true)"
      if [ -z "$entry" ]; then
        err "压缩包内没有找到 img/raw/qcow2/vdi/vmdk 文件。"
        return 1
      fi
      extract_zip_image "$chosen" "$entry"
      ;;
    *)
      IMAGE_PATH="$chosen"
      DISK_FORMAT="$(detect_disk_format "$IMAGE_PATH")"
      ;;
  esac
}

choose_host_ifaces(){
  local -a phys chosen
  local count def iface i macs bridges taps input duplicate
  phys=()
  chosen=()
  while IFS= read -r iface; do
    phys+=("$iface")
  done < <(physical_ifaces)

  printf '\n%s\n' "可选物理网口:"
  if [ "${#phys[@]}" -eq 0 ]; then
    warn "没有自动发现物理网口，你仍可手动输入。"
  else
    for iface in "${phys[@]}"; do
      show_iface_usage "$iface"
    done
  fi

  count="$(read_default "给 RouterOS 配置几个 virtio-net 网口" "3")"
  count="$(normalize_uint "virtio-net 网口数量" "$count" "3" 1 16)"

  for ((i=1; i<=count; i++)); do
    case "$i" in
      1) def="eth1" ;;
      2) def="eth2" ;;
      3) def="eth3" ;;
      *) def="" ;;
    esac
    while true; do
      input="$(read_default "第 $i 个 virtio-net 绑定的宿主机物理网口，输入 none 表示只建内部桥" "$def")"
      input="$(trim "$input")"
      [ -n "$input" ] || input="none"
      if [ "$input" != "none" ] && ! is_ifname "$input"; then
        warn "网口名称非法，请重新输入。"
        continue
      fi
      duplicate=0
      for iface in "${chosen[@]}"; do
        if [ "$input" != "none" ] && [ "$iface" = "$input" ]; then
          duplicate=1
          break
        fi
      done
      if [ "$duplicate" -eq 1 ]; then
        warn "同一个宿主机物理网口不能重复绑定。"
        continue
      fi
      chosen+=("$input")
      break
    done
  done

  VM_IFACES="${chosen[*]}"
  bridges=()
  taps=()
  macs=()
  for ((i=1; i<=count; i++)); do
    bridges+=("br-ros$i")
    taps+=("tap-ros$i")
    macs+=("52:54:00:21:00:$(printf '%02x' "$i")")
  done
  VM_BRIDGES="${bridges[*]}"
  VM_TAPS="${taps[*]}"
  VM_MACS="${macs[*]}"

  ROS_WAN_IFACE="ether1"
  if [ "$count" -ge 2 ]; then
    ROS_LAN_PORTS=""
    for ((i=2; i<=count; i++)); do
      ROS_LAN_PORTS="${ROS_LAN_PORTS:+$ROS_LAN_PORTS }ether$i"
    done
  else
    ROS_LAN_PORTS=""
  fi

  confirm_host_iface_takeover
}

choose_host_net_mode(){
  local choice current
  current="${HOST_NET_MODE:-networkd}"
  printf '\n%s\n' "宿主机网口持久化配置模式:"
  printf '%s\n' "  1. runtime       只在 routeros-chr 服务运行时接管，重启后不保留"
  printf '%s\n' "  2. networkd      写入 systemd-networkd bridge/port 配置"
  printf '%s\n' "  3. nm-unmanaged  只告诉 NetworkManager 不管理这些物理口"
  printf '%s\n' "  4. both          networkd 配置 + NetworkManager unmanaged"
  case "$current" in
    runtime) choice="1" ;;
    nm-unmanaged) choice="3" ;;
    both) choice="4" ;;
    *) choice="2" ;;
  esac
  choice="$(read_default "请选择模式" "$choice")"
  case "$choice" in
    1|runtime) HOST_NET_MODE="runtime"; PERSIST_HOST_NET="0" ;;
    2|networkd) HOST_NET_MODE="networkd"; PERSIST_HOST_NET="1" ;;
    3|nm-unmanaged) HOST_NET_MODE="nm-unmanaged"; PERSIST_HOST_NET="1" ;;
    4|both) HOST_NET_MODE="both"; PERSIST_HOST_NET="1" ;;
    *)
      warn "选择无效，使用当前模式: $current"
      HOST_NET_MODE="$current"
      case "$HOST_NET_MODE" in runtime) PERSIST_HOST_NET="0" ;; *) PERSIST_HOST_NET="1" ;; esac
      ;;
  esac
}

resize_disk_image(){
  local size
  if ! has_cmd qemu-img; then
    warn "缺少 qemu-img，跳过硬盘调整。"
    return 0
  fi
  printf '\n'
  ls -lh "$IMAGE_PATH" 2>/dev/null || true
  if [ "${DISK_FORMAT:-raw}" != "raw" ]; then
    qemu_img_format_probe "$IMAGE_PATH" 3 >/dev/null || warn "镜像格式探测超时或失败，已跳过详细信息显示。"
  fi
  size="$(read_default "如需扩容请输入目标大小，例如 2G、4G；直接回车跳过" "")"
  [ -z "$size" ] && return 0
  if ! is_size_value "$size"; then
    err "大小格式无效，请使用 2G、4096M 这类格式。"
    return 1
  fi
  warn "只建议扩容，不建议缩小镜像。RouterOS 内部文件系统扩展由 RouterOS 自己处理。"
  if confirm "确认执行 qemu-img resize $IMAGE_PATH $size" "n"; then
    qemu-img resize "$IMAGE_PATH" "$size" && ok "镜像大小已调整。"
  fi
}

write_runtime_files(){
  mkdir -p "$CONFIG_DIR" "$LIB_DIR" /run/routeros

  atomic_write "$HOSTNET_SCRIPT" 0755 <<'EOF_HOSTNET'
#!/usr/bin/env bash
set -euo pipefail
CONFIG_FILE="/etc/routerosinstall/config.env"
[ -r "$CONFIG_FILE" ] && . "$CONFIG_FILE"

ACTION="${1:-up}"
mkdir -p /run/routeros
STATE_FILE="/run/routeros/hostnet.state"
ROLLBACK_SCRIPT="/etc/routerosinstall/last-hostnet-rollback.sh"

read -r -a ifaces <<< "${VM_IFACES:-}"
read -r -a bridges <<< "${VM_BRIDGES:-}"
read -r -a taps <<< "${VM_TAPS:-}"
queues="${NET_QUEUES:-1}"

is_uint(){
  [[ "${1:-}" =~ ^[0-9]+$ ]]
}

is_ifname(){
  [[ "${1:-}" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]]
}

is_allowed_danger_iface(){
  local iface="$1" allowed
  for allowed in ${ALLOW_DANGEROUS_IFACES:-}; do
    [ "$iface" = "$allowed" ] && return 0
  done
  return 1
}

iface_has_host_network(){
  local iface="$1"
  ip -o addr show dev "$iface" 2>/dev/null | grep -q . && return 0
  ip route show dev "$iface" 2>/dev/null | grep -q . && return 0
  return 1
}

management_ifaces(){
  {
    ip route show default 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="dev") print $(i+1)}'
    if [ -n "${SSH_CONNECTION:-}" ]; then
      local remote="${SSH_CONNECTION%% *}"
      ip route get "$remote" 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="dev") print $(i+1)}'
    fi
  } | awk 'NF && !seen[$0]++'
}

iface_is_management(){
  local iface="$1" mgmt
  while IFS= read -r mgmt; do
    [ "$iface" = "$mgmt" ] && return 0
  done < <(management_ifaces)
  return 1
}

write_rollback_script(){
  local iface addr route tmp
  mkdir -p "$(dirname "$ROLLBACK_SCRIPT")"
  tmp="$(mktemp "$(dirname "$ROLLBACK_SCRIPT")/.rollback.XXXXXX")" || return 1
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' 'set -u'
    printf '# Generated by routerosinstall hostnet at %s\n' "$(date -Is 2>/dev/null || date)"
    for iface in "${ifaces[@]}"; do
      [ -n "$iface" ] || continue
      [ "$iface" = "none" ] && continue
      ip link show "$iface" >/dev/null 2>&1 || continue
      printf 'ip link set %q nomaster 2>/dev/null || true\n' "$iface"
      printf 'ip link set %q up 2>/dev/null || true\n' "$iface"
      while IFS= read -r addr; do
        [ -n "$addr" ] || continue
        printf 'ip addr add %q dev %q 2>/dev/null || true\n' "$addr" "$iface"
      done < <(ip -o addr show dev "$iface" 2>/dev/null | awk '{print $4}')
      while IFS= read -r route; do
        [ -n "$route" ] || continue
        printf 'ip route replace %s 2>/dev/null || true\n' "$route"
      done < <(ip route show dev "$iface" 2>/dev/null)
    done
  } > "$tmp"
  chmod 0700 "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$ROLLBACK_SCRIPT"
}

preflight_up(){
  local i br tap iface bad=0
  is_uint "$queues" || queues=1
  [ "$queues" -ge 1 ] || queues=1
  if [ "${#bridges[@]}" -eq 0 ]; then
    echo "routerosinstall: no bridge configured" >&2
    return 1
  fi
  for i in "${!bridges[@]}"; do
    br="${bridges[$i]}"
    tap="${taps[$i]:-}"
    iface="${ifaces[$i]:-none}"
    if ! is_ifname "$br"; then
      echo "routerosinstall: invalid bridge name: $br" >&2
      bad=1
    fi
    if [ -n "$tap" ] && ! is_ifname "$tap"; then
      echo "routerosinstall: invalid tap name: $tap" >&2
      bad=1
    fi
    if [ -n "$iface" ] && [ "$iface" != "none" ]; then
      if ! is_ifname "$iface"; then
        echo "routerosinstall: invalid host iface name: $iface" >&2
        bad=1
      elif ! ip link show "$iface" >/dev/null 2>&1; then
        echo "routerosinstall: host iface not found: $iface" >&2
        bad=1
      elif { iface_is_management "$iface" || iface_has_host_network "$iface"; } && ! is_allowed_danger_iface "$iface"; then
        echo "routerosinstall: refusing to take over active/management iface without prior YES confirmation: $iface" >&2
        bad=1
      fi
    fi
  done
  [ "$bad" -eq 0 ]
}

create_tap(){
  local tap="$1"
  if ip link show "$tap" >/dev/null 2>&1; then
    printf 'tap %s existing\n' "$tap" >> "$STATE_FILE"
    return 0
  fi
  if [ "${queues:-1}" -gt 1 ] 2>/dev/null; then
    ip tuntap add dev "$tap" mode tap multi_queue 2>/dev/null || ip tuntap add dev "$tap" mode tap
  else
    ip tuntap add dev "$tap" mode tap
  fi
  printf 'tap %s created\n' "$tap" >> "$STATE_FILE"
}

bridge_created_by_us(){
  local br="$1"
  grep -qxF "bridge $br created" "$STATE_FILE" 2>/dev/null
}

tap_created_by_us(){
  local tap="$1"
  grep -qxF "tap $tap created" "$STATE_FILE" 2>/dev/null
}

case "$ACTION" in
  up)
    preflight_up
    : > "$STATE_FILE"
    write_rollback_script || true
    modprobe tun 2>/dev/null || true
    modprobe vhost_net 2>/dev/null || true
    for i in "${!bridges[@]}"; do
      br="${bridges[$i]}"
      tap="${taps[$i]:-}"
      iface="${ifaces[$i]:-none}"
      if ip link show "$br" >/dev/null 2>&1; then
        printf 'bridge %s existing\n' "$br" >> "$STATE_FILE"
      else
        ip link add name "$br" type bridge
        printf 'bridge %s created\n' "$br" >> "$STATE_FILE"
      fi
      ip link set "$br" up
      if [ -n "$tap" ]; then
        create_tap "$tap"
        ip link set "$tap" master "$br"
        ip link set "$tap" up
      fi
      if [ -n "$iface" ] && [ "$iface" != "none" ]; then
        if ip link show "$iface" >/dev/null 2>&1; then
          ip addr flush dev "$iface" 2>/dev/null || true
          ip link set "$iface" nomaster 2>/dev/null || true
          ip link set "$iface" up 2>/dev/null || true
          if ! ip link set "$iface" master "$br" 2>/dev/null; then
            echo "routerosinstall: failed to attach $iface to $br" >&2
            exit 1
          fi
          current_master="$(basename "$(readlink -f "/sys/class/net/$iface/master" 2>/dev/null)" 2>/dev/null || true)"
          if [ "$current_master" != "$br" ]; then
            echo "routerosinstall: $iface is still attached to ${current_master:-none}, expected $br" >&2
            exit 1
          fi
        else
          echo "routerosinstall: host iface $iface not found" >&2
        fi
      fi
    done
    ;;
  down)
    for i in "${!bridges[@]}"; do
      br="${bridges[$i]}"
      tap="${taps[$i]:-}"
      iface="${ifaces[$i]:-none}"
      if [ -n "$iface" ] && [ "$iface" != "none" ] && ip link show "$iface" >/dev/null 2>&1; then
        ip link set "$iface" nomaster 2>/dev/null || true
      fi
      if [ -n "$tap" ] && ip link show "$tap" >/dev/null 2>&1; then
        ip link set "$tap" down 2>/dev/null || true
        if tap_created_by_us "$tap"; then
          ip link delete "$tap" 2>/dev/null || true
        fi
      fi
      if ip link show "$br" >/dev/null 2>&1; then
        if bridge_created_by_us "$br"; then
          ip link set "$br" down 2>/dev/null || true
          ip link delete "$br" type bridge 2>/dev/null || true
        fi
      fi
    done
    rm -f "$STATE_FILE" 2>/dev/null || true
    ;;
  *)
    echo "usage: $0 up|down" >&2
    exit 2
    ;;
esac
EOF_HOSTNET

  atomic_write "$START_SCRIPT" 0755 <<'EOF_START'
#!/usr/bin/env bash
set -euo pipefail
CONFIG_FILE="/etc/routerosinstall/config.env"
[ -r "$CONFIG_FILE" ] && . "$CONFIG_FILE"

QEMU_BIN="${QEMU_BIN:-qemu-system-aarch64}"
IMAGE_PATH="${IMAGE_PATH:-/root/routeros.img}"
DISK_FORMAT="${DISK_FORMAT:-raw}"
VM_CPUS="${VM_CPUS:-4}"
VM_MEMORY_MB="${VM_MEMORY_MB:-1024}"
NET_QUEUES="${NET_QUEUES:-1}"
SERIAL_SOCK="${SERIAL_SOCK:-/run/routeros/serial.sock}"
MONITOR_SOCK="${MONITOR_SOCK:-/run/routeros/monitor.sock}"
PID_FILE="${PID_FILE:-/run/routeros/routeros-chr.pid}"

read -r -a taps <<< "${VM_TAPS:-tap-ros1 tap-ros2 tap-ros3}"
read -r -a macs <<< "${VM_MACS:-52:54:00:21:00:01 52:54:00:21:00:02 52:54:00:21:00:03}"

is_uint(){
  [[ "${1:-}" =~ ^[0-9]+$ ]]
}

is_ifname(){
  [[ "${1:-}" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]]
}

is_mac(){
  [[ "${1:-}" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]
}

qemu_img_format_probe(){
  local path="$1" timeout_s="${2:-3}" actual
  command -v qemu-img >/dev/null 2>&1 || return 1
  command -v timeout >/dev/null 2>&1 || return 1
  [ -f "$path" ] || return 1

  if ! actual="$(timeout "$timeout_s" qemu-img info "$path" 2>/dev/null | awk -F': ' '/^file format:/ {print $2; exit}')"; then
    return 1
  fi
  case "$actual" in
    raw|qcow2|vdi|vmdk) printf '%s' "$actual"; return 0 ;;
  esac
  return 1
}

find_aarch64_efi_firmware(){
  local fw
  for fw in \
    /usr/share/qemu-efi-aarch64/QEMU_EFI.fd \
    /usr/share/AAVMF/AAVMF_CODE.fd \
    /usr/share/AAVMF/AAVMF_CODE.no-secboot.fd; do
    [ -r "$fw" ] && { printf '%s\n' "$fw"; return 0; }
  done
  return 1
}

preflight_start(){
  local tap mac actual arch bad=0
  if ! command -v "$QEMU_BIN" >/dev/null 2>&1; then
    echo "routerosinstall: QEMU not found: $QEMU_BIN" >&2
    return 1
  fi
  if [ ! -f "$IMAGE_PATH" ]; then
    echo "routerosinstall: image not found: $IMAGE_PATH" >&2
    return 1
  fi
  if ! is_uint "$VM_CPUS" || [ "$VM_CPUS" -lt 1 ]; then
    echo "routerosinstall: invalid VM_CPUS: $VM_CPUS" >&2
    bad=1
  fi
  if ! is_uint "$VM_MEMORY_MB" || [ "$VM_MEMORY_MB" -lt 128 ]; then
    echo "routerosinstall: invalid VM_MEMORY_MB: $VM_MEMORY_MB" >&2
    bad=1
  fi
  if ! is_uint "$NET_QUEUES" || [ "$NET_QUEUES" -lt 1 ]; then
    echo "routerosinstall: invalid NET_QUEUES: $NET_QUEUES" >&2
    bad=1
  fi
  case "${DISK_FORMAT,,}" in
    raw|qcow2|vdi|vmdk) ;;
    *) echo "routerosinstall: unsupported DISK_FORMAT: $DISK_FORMAT" >&2; bad=1 ;;
  esac
  actual=""
  case "${IMAGE_PATH,,}" in
    *.img|*.raw) ;;
    *) actual="$(qemu_img_format_probe "$IMAGE_PATH" 3 || true)" ;;
  esac
  if [ -n "$actual" ] && [ "$actual" != "$DISK_FORMAT" ]; then
    echo "routerosinstall: configured DISK_FORMAT=$DISK_FORMAT, qemu-img reports $actual; using reported format" >&2
    DISK_FORMAT="$actual"
  fi
  for tap in "${taps[@]}"; do
    if ! is_ifname "$tap"; then
      echo "routerosinstall: invalid tap name: $tap" >&2
      bad=1
    elif ! ip link show "$tap" >/dev/null 2>&1; then
      echo "routerosinstall: tap is missing, hostnet pre-start may have failed: $tap" >&2
      bad=1
    fi
  done
  for mac in "${macs[@]}"; do
    if ! is_mac "$mac"; then
      echo "routerosinstall: invalid MAC address: $mac" >&2
      bad=1
    fi
  done
  arch="$(uname -m)"
  if { [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; } && ! find_aarch64_efi_firmware >/dev/null; then
    echo "routerosinstall: missing AArch64 UEFI firmware; install qemu-efi-aarch64" >&2
    bad=1
  fi
  [ "$bad" -eq 0 ]
}

mkdir -p "$(dirname "$SERIAL_SOCK")"
rm -f "$SERIAL_SOCK" "$MONITOR_SOCK" "$PID_FILE"

preflight_start

arch="$(uname -m)"
efi_fw=""
args=(-name routeros-chr)
if { [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; } && [ -e /dev/kvm ]; then
  efi_fw="$(find_aarch64_efi_firmware)"
  args+=(-machine virt,accel=kvm,gic-version=3 -cpu host -bios "$efi_fw")
elif [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then
  efi_fw="$(find_aarch64_efi_firmware)"
  args+=(-machine virt -cpu cortex-a72 -bios "$efi_fw")
else
  echo "routerosinstall: unsupported host arch for this script: $arch" >&2
  exit 1
fi
args+=(-smp "$VM_CPUS" -m "${VM_MEMORY_MB}M")
args+=(-drive "file=$IMAGE_PATH,if=virtio,format=$DISK_FORMAT,cache=none,aio=threads,discard=unmap")

vhost="off"
[ -e /dev/vhost-net ] && vhost="on"
if ! [[ "$NET_QUEUES" =~ ^[0-9]+$ ]] || [ "$NET_QUEUES" -lt 1 ]; then
  NET_QUEUES=1
fi
vectors=$((NET_QUEUES * 2 + 2))
for i in "${!taps[@]}"; do
  tap="${taps[$i]}"
  mac="${macs[$i]:-52:54:00:21:00:ff}"
  netid="net$((i+1))"
  args+=(-netdev "tap,id=$netid,ifname=$tap,script=no,downscript=no,vhost=$vhost,queues=$NET_QUEUES")
  args+=(-device "virtio-net-pci,netdev=$netid,mac=$mac,mq=on,vectors=$vectors,romfile=")
done

args+=(-serial "unix:$SERIAL_SOCK,server,nowait")
args+=(-monitor "unix:$MONITOR_SOCK,server,nowait")
args+=(-pidfile "$PID_FILE" -display none -nographic)

exec "$QEMU_BIN" "${args[@]}"
EOF_START

  atomic_write "$CONSOLE_CMD" 0755 <<'EOF_CONSOLE'
#!/usr/bin/env bash
CONFIG_FILE="/etc/routerosinstall/config.env"
[ -r "$CONFIG_FILE" ] && . "$CONFIG_FILE"
SERIAL_SOCK="${SERIAL_SOCK:-/run/routeros/serial.sock}"

socket_ready(){
  [ -S "$SERIAL_SOCK" ] || return 1
  if command -v ss >/dev/null 2>&1; then
    ss -xl 2>/dev/null | awk '{print $5}' | grep -Fxq "$SERIAL_SOCK"
  else
    return 0
  fi
}

show_failure_hint(){
  echo "RouterOS 串口未就绪: $SERIAL_SOCK" >&2
  if command -v systemctl >/dev/null 2>&1; then
    systemctl --no-pager --full status routeros-chr.service 2>/dev/null | sed -n '1,18p' >&2 || true
    echo "更多日志: journalctl -u routeros-chr.service -n 80 --no-pager" >&2
  fi
}

if ! systemctl is-active --quiet routeros-chr.service 2>/dev/null; then
  echo "RouterOS 服务未运行，正在启动 routeros-chr.service..." >&2
  rm -f "$SERIAL_SOCK" 2>/dev/null || true
  if ! systemctl start routeros-chr.service; then
    show_failure_hint
    exit 1
  fi
fi

tries=0
while [ "$tries" -lt 30 ]; do
  socket_ready && break
  tries=$((tries + 1))
  sleep 0.2
done

if ! socket_ready; then
  show_failure_hint
  exit 1
fi
echo "进入 RouterOS 控制台。退出方式: 按 Ctrl+]。"
exec socat -,raw,echo=0,escape=0x1d "UNIX-CONNECT:$SERIAL_SOCK"
EOF_CONSOLE

  atomic_write "$SERVICE_FILE" 0644 <<EOF_SERVICE
[Unit]
Description=RouterOS CHR virtual machine
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=$HOSTNET_SCRIPT up
ExecStart=$START_SCRIPT
ExecStopPost=$HOSTNET_SCRIPT down
Restart=on-failure
RestartSec=3
KillSignal=SIGTERM
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF_SERVICE

  write_persistent_network_files

  systemctl daemon-reload 2>/dev/null || true
}

remove_persistent_network_files(){
  rm -f "$NETWORKD_PREFIX"-*.netdev "$NETWORKD_PREFIX"-*.network 2>/dev/null || true
  rm -f "$NETWORKD_LEGACY_PREFIX"-*.netdev "$NETWORKD_LEGACY_PREFIX"-*.network 2>/dev/null || true
  rm -f "$NM_UNMANAGED_CONF" 2>/dev/null || true
}

remove_routeros_dir(){
  local target="$1"
  case "$target" in
    "$LIB_DIR"|"$CONFIG_DIR")
      rm -rf -- "$target"
      ;;
    *)
      err "拒绝删除非 routerosinstall 固定目录: $target"
      return 1
      ;;
  esac
}

write_networkd_files(){
  local -a ifaces bridges
  local i iface br
  read -r -a ifaces <<< "$VM_IFACES"
  read -r -a bridges <<< "$VM_BRIDGES"
  mkdir -p /etc/systemd/network

  rm -f "$NETWORKD_PREFIX"-*.netdev "$NETWORKD_PREFIX"-*.network 2>/dev/null || true
  rm -f "$NETWORKD_LEGACY_PREFIX"-*.netdev "$NETWORKD_LEGACY_PREFIX"-*.network 2>/dev/null || true

  for i in "${!bridges[@]}"; do
    br="${bridges[$i]}"
    iface="${ifaces[$i]:-none}"
    atomic_write "$NETWORKD_PREFIX-$br.netdev" 0644 <<EOF_NETDEV
[NetDev]
Name=$br
Kind=bridge
EOF_NETDEV
    atomic_write "$NETWORKD_PREFIX-$br.network" 0644 <<EOF_BRNET
[Match]
Name=$br

[Network]
LinkLocalAddressing=no
IPv6AcceptRA=no
EOF_BRNET
    if [ -n "$iface" ] && [ "$iface" != "none" ]; then
      atomic_write "$NETWORKD_PREFIX-$iface.network" 0644 <<EOF_PORTNET
[Match]
Name=$iface

[Link]
RequiredForOnline=no
ActivationPolicy=up

[Network]
Bridge=$br
ConfigureWithoutCarrier=yes
IgnoreCarrierLoss=yes
LinkLocalAddressing=no
IPv6AcceptRA=no
EOF_PORTNET
    fi
  done
}

write_nm_unmanaged_file(){
  local iface unmanaged=""
  mkdir -p /etc/NetworkManager/conf.d
  for iface in $VM_IFACES; do
    [ -n "$iface" ] || continue
    [ "$iface" = "none" ] && continue
    unmanaged="${unmanaged:+$unmanaged; }interface-name:$iface"
  done
  if [ -n "$unmanaged" ]; then
    atomic_write "$NM_UNMANAGED_CONF" 0644 <<EOF_NM
[keyfile]
unmanaged-devices=$unmanaged
EOF_NM
  fi
}

reload_persistent_network_managers(){
  local mode="${HOST_NET_MODE:-networkd}"
  local iface br

  case "$mode" in
    networkd|both|runtime)
      if has_cmd networkctl; then
        networkctl reload 2>/dev/null || true
        for br in $VM_BRIDGES; do
          [ -n "$br" ] || continue
          networkctl reconfigure "$br" 2>/dev/null || true
        done
        for iface in $VM_IFACES; do
          [ -n "$iface" ] || continue
          [ "$iface" = "none" ] && continue
          networkctl reconfigure "$iface" 2>/dev/null || true
        done
      elif has_cmd systemctl; then
        systemctl reload systemd-networkd 2>/dev/null || true
      fi
      ;;
  esac

  case "$mode" in
    nm-unmanaged|both|runtime)
      if has_cmd systemctl; then
        systemctl reload NetworkManager 2>/dev/null || systemctl restart NetworkManager 2>/dev/null || true
      fi
      ;;
  esac
}

write_persistent_network_files(){
  case "${HOST_NET_MODE:-networkd}" in
    runtime)
      remove_persistent_network_files
      ;;
    networkd)
      rm -f "$NM_UNMANAGED_CONF" 2>/dev/null || true
      write_networkd_files
      ;;
    nm-unmanaged)
      rm -f "$NETWORKD_PREFIX"-*.netdev "$NETWORKD_PREFIX"-*.network 2>/dev/null || true
      rm -f "$NETWORKD_LEGACY_PREFIX"-*.netdev "$NETWORKD_LEGACY_PREFIX"-*.network 2>/dev/null || true
      write_nm_unmanaged_file
      ;;
    both)
      write_networkd_files
      write_nm_unmanaged_file
      ;;
    *)
      warn "未知持久化模式 ${HOST_NET_MODE:-空}，按 runtime 处理。"
      HOST_NET_MODE="runtime"
      PERSIST_HOST_NET="0"
      remove_persistent_network_files
      ;;
  esac

  reload_persistent_network_managers
}

menu_vm_config(){
  print_title
  load_config

  choose_image_from_root || { pause; return 1; }
  if [ ! -f "$IMAGE_PATH" ]; then
    warn "镜像路径当前不存在: $IMAGE_PATH"
  fi

  local detected_cpu default_cpu
  detected_cpu="$(nproc 2>/dev/null || echo 4)"
  default_cpu="$VM_CPUS"
  if [ -z "$default_cpu" ] || [ "$default_cpu" = "0" ]; then
    default_cpu="$detected_cpu"
  fi
  VM_CPUS="$(read_default "分配给 RouterOS 的 vCPU 数量，空闲时按需调度，不会固定占满" "$default_cpu")"
  VM_MEMORY_MB="$(read_default "分配内存 MB" "$VM_MEMORY_MB")"
  NET_QUEUES="$(read_default "virtio-net 队列数，建议 1-4" "$NET_QUEUES")"
  QEMU_BIN="$(read_default "QEMU 可执行文件" "$QEMU_BIN")"

  choose_host_ifaces || { pause; return 1; }

  choose_host_net_mode

  validate_vm_config || { pause; return 1; }

  resize_disk_image || { pause; return 1; }
  DISK_FORMAT="$(detect_disk_format "$IMAGE_PATH")"
  save_config
  write_runtime_files

  printf '\n'
  ok "虚拟机参数已保存。"
  printf '%s\n' "镜像: $IMAGE_PATH ($DISK_FORMAT)"
  printf '%s\n' "CPU/内存: ${VM_CPUS} vCPU / ${VM_MEMORY_MB} MB"
  printf '%s\n' "宿主机网口: $VM_IFACES"
  printf '%s\n' "桥/tap: $VM_BRIDGES / $VM_TAPS"
  printf '%s\n' "宿主机网络持久化: $HOST_NET_MODE"
  warn "如果选中的网口原来属于宿主机网络，启动 RouterOS 时会被接管，宿主机不再直接在这些网口上拿 IP。"
  pause
}

ip_to_int(){
  local IFS=. a b c d
  read -r a b c d <<< "$1"
  printf '%u' $(( (10#$a << 24) + (10#$b << 16) + (10#$c << 8) + 10#$d ))
}

int_to_ip(){
  local n="$1"
  printf '%u.%u.%u.%u' "$(( (n >> 24) & 255 ))" "$(( (n >> 16) & 255 ))" "$(( (n >> 8) & 255 ))" "$(( n & 255 ))"
}

cidr_network(){
  local ip="$1" prefix="$2" ipn mask net
  ipn="$(ip_to_int "$ip")"
  prefix=$((10#$prefix))
  if [ "$prefix" -eq 0 ]; then
    mask=0
  else
    mask=$(( (0xffffffff << (32 - prefix)) & 0xffffffff ))
  fi
  net=$(( ipn & mask ))
  int_to_ip "$net"
}

ros_quote(){
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

build_preset_rsc(){
  mkdir -p "$CONFIG_DIR"
  validate_routeros_config || return 1
  local network lan_cidr identity_q wan_q bridge_q dns_clean lan_port_cmds port port_q
  network="$(cidr_network "$ROS_LAN_IP" "$ROS_LAN_PREFIX")"
  lan_cidr="$network/$ROS_LAN_PREFIX"
  identity_q="$(ros_quote "$ROS_IDENTITY")"
  wan_q="$(ros_quote "$ROS_WAN_IFACE")"
  bridge_q="$(ros_quote "$ROS_LAN_BRIDGE")"
  dns_clean="$(strip_spaces "$ROS_DNS_SERVERS")"
  lan_port_cmds=""
  for port in $ROS_LAN_PORTS; do
    port_q="$(ros_quote "$port")"
    lan_port_cmds+=$(printf ':do { /interface bridge port add bridge=%s interface=%s comment="routerosinstall: LAN port" } on-error={}' "$bridge_q" "$port_q")
    lan_port_cmds+=$'\n'
  done

  atomic_write "$PRESET_RSC" 0644 <<EOF_RSC
# Generated by routerosinstall at $(date -Is 2>/dev/null || date)

/system identity set name=$identity_q

:do { /interface ethernet set [find default-name=$wan_q] name=$wan_q comment="routerosinstall: WAN" } on-error={}
:do { /interface ethernet set [find name=$wan_q] comment="routerosinstall: WAN" } on-error={}
:do { /interface bridge add name=$bridge_q comment="routerosinstall: LAN bridge" protocol-mode=rstp } on-error={}
:do { /interface bridge set [find name=$bridge_q] comment="routerosinstall: LAN bridge" protocol-mode=rstp } on-error={}

/interface bridge port remove [find comment="routerosinstall: LAN port"]
$lan_port_cmds

/ip dhcp-client remove [find comment="routerosinstall: WAN DHCP"]
/ip dhcp-client add interface=$wan_q add-default-route=yes use-peer-dns=no disabled=no comment="routerosinstall: WAN DHCP"

/ip address remove [find comment="routerosinstall: LAN gateway"]
/ip address add address=$ROS_LAN_IP/$ROS_LAN_PREFIX interface=$bridge_q comment="routerosinstall: LAN gateway"

/ip pool remove [find name="pool-lan"]
/ip pool add name=pool-lan ranges=$ROS_DHCP_START-$ROS_DHCP_END

/ip dhcp-server remove [find name="dhcp-lan"]
/ip dhcp-server add name=dhcp-lan interface=$bridge_q address-pool=pool-lan lease-time=12h disabled=no
/ip dhcp-server network remove [find comment="routerosinstall: LAN DHCP network"]
/ip dhcp-server network add address=$lan_cidr gateway=$ROS_LAN_IP dns-server=$ROS_LAN_IP comment="routerosinstall: LAN DHCP network"

/ip dns set allow-remote-requests=yes servers=$dns_clean

/ip firewall nat remove [find comment~"routerosinstall:"]
/ip firewall nat add chain=srcnat out-interface=$wan_q action=masquerade comment="routerosinstall: NAT LAN to WAN"

/ip firewall filter remove [find comment~"routerosinstall:"]
/ip firewall filter add chain=input action=accept connection-state=established,related comment="routerosinstall: allow established input"
/ip firewall filter add chain=input action=drop connection-state=invalid comment="routerosinstall: drop invalid input"
/ip firewall filter add chain=input action=accept in-interface=$bridge_q comment="routerosinstall: allow LAN to router"
/ip firewall filter add chain=input action=accept protocol=icmp comment="routerosinstall: allow ping"
/ip firewall filter add chain=forward action=fasttrack-connection connection-state=established,related comment="routerosinstall: fasttrack established related"
/ip firewall filter add chain=forward action=accept connection-state=established,related comment="routerosinstall: accept established related"
/ip firewall filter add chain=forward action=drop connection-state=invalid comment="routerosinstall: drop invalid forward"
/ip firewall filter add chain=forward action=accept in-interface=$bridge_q out-interface=$wan_q comment="routerosinstall: allow LAN to WAN"

/ip service enable ssh
/ip service enable www
/ip service enable winbox
EOF_RSC
}

show_routeros_preset_values(){
  printf '%s\n' "当前 RouterOS 预设置:"
  printf '  %-18s %s\n' "identity" "$ROS_IDENTITY"
  printf '  %-18s %s\n' "WAN" "$ROS_WAN_IFACE DHCP"
  printf '  %-18s %s\n' "LAN bridge" "$ROS_LAN_BRIDGE"
  printf '  %-18s %s\n' "LAN ports" "${ROS_LAN_PORTS:-无}"
  printf '  %-18s %s/%s\n' "LAN IP" "$ROS_LAN_IP" "$ROS_LAN_PREFIX"
  printf '  %-18s %s-%s\n' "DHCP pool" "$ROS_DHCP_START" "$ROS_DHCP_END"
  printf '  %-18s %s\n' "DNS" "$ROS_DNS_SERVERS"
}

edit_routeros_preset(){
  show_routeros_preset_values
  printf '\n'
  ROS_IDENTITY="$(read_default "RouterOS identity" "$ROS_IDENTITY")"
  ROS_WAN_IFACE="$(read_default "WAN 口名称" "$ROS_WAN_IFACE")"
  ROS_LAN_BRIDGE="$(read_default "LAN bridge 名称" "$ROS_LAN_BRIDGE")"
  ROS_LAN_PORTS="$(read_default "LAN 口列表，用空格分隔" "$ROS_LAN_PORTS")"
  ROS_LAN_IP="$(read_default "LAN IP" "$ROS_LAN_IP")"
  ROS_LAN_PREFIX="$(read_default "LAN 掩码前缀" "$ROS_LAN_PREFIX")"
  ROS_DHCP_START="$(read_default "DHCP 起始地址" "$ROS_DHCP_START")"
  ROS_DHCP_END="$(read_default "DHCP 结束地址" "$ROS_DHCP_END")"
  ROS_DNS_SERVERS="$(read_default "RouterOS 上游 DNS，逗号分隔" "$ROS_DNS_SERVERS")"
  validate_routeros_config || return 1
  save_config
  build_preset_rsc
  ok "预设置已保存到 $PRESET_RSC"
}

apply_preset_ssh(){
  local target
  build_preset_rsc || return 1
  target="$(read_default "RouterOS SSH 地址" "$ROS_LAN_IP")"
  if ! has_cmd ssh; then
    err "缺少 ssh 客户端，请先执行菜单 1。"
    return 1
  fi
  warn "将通过 SSH 把预设置导入 RouterOS。如果 RouterOS 已有密码，请按提示输入。"
  ssh \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o PubkeyAuthentication=no \
    -o PreferredAuthentications=none,password,keyboard-interactive \
    -o ConnectTimeout=8 \
    "admin@$target" < "$PRESET_RSC"
}

apply_preset_serial(){
  build_preset_rsc || return 1
  if ! has_cmd socat; then
    err "缺少 socat，请先执行菜单 1。"
    return 1
  fi
  if [ ! -S "$SERIAL_SOCK" ]; then
    err "RouterOS 串口 socket 不存在: $SERIAL_SOCK"
    warn "请先在菜单 5 启动 RouterOS。"
    return 1
  fi
  warn "串口自动发送配置是实验功能，RouterOS 首次登录、提示改密码或终端回显异常时可能失败。"
  warn "更稳的方式是先进 routeros 控制台确认已登录，再用 SSH 应用预设置。"
  if [ "$(read_default "确认要通过串口自动发送配置请输入 YES" "")" != "YES" ]; then
    warn "已取消串口自动应用。"
    return 1
  fi
  {
    sleep 1
    printf '\r'
    sleep 1
    printf 'admin\r'
    sleep 1
    printf '\r'
    sleep 2
    while IFS= read -r line; do
      printf '%s\r' "$line"
      sleep 0.05
    done < "$PRESET_RSC"
    sleep 1
    printf '\r/quit\r'
  } | socat -T 60 - "UNIX-CONNECT:$SERIAL_SOCK"
}

menu_routeros_preset(){
  load_config
  while true; do
    print_title
    show_routeros_preset_values
    printf '\n'
    printf '%s\n' "1. 修改预设置参数"
    printf '%s\n' "2. 生成/刷新 RouterOS .rsc 预设置脚本"
    printf '%s\n' "3. 通过 SSH 应用预设置"
    printf '%s\n' "4. 通过串口 socket 尝试应用预设置"
    printf '%s\n' "5. 查看预设置脚本"
    printf '%s\n' "0. 返回主菜单"
    printf '%s' "请选择: "
    local choice
    IFS= read -r choice || true
    case "$choice" in
      1) edit_routeros_preset; pause ;;
      2) build_preset_rsc && ok "已生成 $PRESET_RSC"; pause ;;
      3) apply_preset_ssh; pause ;;
      4) apply_preset_serial; pause ;;
      5) build_preset_rsc && sed -n '1,220p' "$PRESET_RSC"; pause ;;
      0) return ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

service_status(){
  if [ -f "$SERVICE_FILE" ]; then
    systemctl --no-pager --full status routeros-chr.service 2>/dev/null | sed -n '1,18p' || true
  else
    warn "routeros-chr.service 尚未生成，请先执行菜单 3。"
  fi
}

uninstall_vm_service(){
  local keep_config="y" remove_net="y"
  warn "这会停止并删除 RouterOS systemd 服务、hostnet/start 脚本和 routeros 控制台命令。"
  systemctl stop routeros-chr.service 2>/dev/null || true
  systemctl disable routeros-chr.service 2>/dev/null || true
  if [ -x "$HOSTNET_SCRIPT" ]; then
    "$HOSTNET_SCRIPT" down 2>/dev/null || true
  fi

  confirm "是否保留镜像和 $CONFIG_DIR 配置文件" "y" && keep_config="y" || keep_config="n"
  confirm "是否删除脚本写入的 systemd-networkd/NetworkManager 持久化网口配置" "y" && remove_net="y" || remove_net="n"

  rm -f "$SERVICE_FILE" "$CONSOLE_CMD"
  remove_routeros_dir "$LIB_DIR"
  rm -f /run/routeros/hostnet.state /run/routeros/serial.sock /run/routeros/monitor.sock /run/routeros/routeros-chr.pid 2>/dev/null || true
  if [ "$remove_net" = "y" ]; then
    remove_persistent_network_files
  fi
  if [ "$keep_config" = "n" ]; then
    remove_routeros_dir "$CONFIG_DIR"
  fi
  systemctl daemon-reload 2>/dev/null || true
  if [ "$remove_net" = "y" ]; then
    systemctl restart systemd-networkd 2>/dev/null || true
    systemctl reload NetworkManager 2>/dev/null || true
  fi
  ok "RouterOS 虚拟机服务已卸载。镜像文件不会自动删除，请手动确认后处理。"
}

menu_service_manage(){
  load_config
  while true; do
    print_title
    service_status
    printf '\n'
    printf '%s\n' "1. 启动 RouterOS"
    printf '%s\n' "2. 关闭 RouterOS"
    printf '%s\n' "3. 重启 RouterOS"
    printf '%s\n' "4. 设置开机自启动"
    printf '%s\n' "5. 取消开机自启动"
    printf '%s\n' "6. 进入 RouterOS 控制台"
    printf '%s\n' "7. 卸载 RouterOS 虚拟机服务"
    printf '%s\n' "0. 返回主菜单"
    printf '%s' "请选择: "
    local choice
    IFS= read -r choice || true
    case "$choice" in
      1)
        write_runtime_files
        if systemctl start routeros-chr.service; then
          ok "RouterOS 已启动。"
          info "在命令行输入 routeros 可进入 RouterOS 控制台。"
          info "在 RouterOS 控制台中按 Ctrl+] 可退出控制台。"
        else
          err "RouterOS 启动失败，请查看: journalctl -u routeros-chr.service -n 80 --no-pager"
        fi
        pause
        ;;
      2)
        if systemctl stop routeros-chr.service; then
          ok "RouterOS 已关闭。"
        else
          err "RouterOS 关闭失败，请查看 systemd 状态。"
        fi
        pause
        ;;
      3)
        write_runtime_files
        if systemctl restart routeros-chr.service; then
          ok "RouterOS 已重启。"
        else
          err "RouterOS 重启失败，请查看: journalctl -u routeros-chr.service -n 80 --no-pager"
        fi
        pause
        ;;
      4)
        write_runtime_files
        if systemctl enable routeros-chr.service; then
          ok "已设置开机自启动。"
        else
          err "设置开机自启动失败。"
        fi
        pause
        ;;
      5)
        if systemctl disable routeros-chr.service; then
          ok "已取消开机自启动。"
        else
          err "取消开机自启动失败。"
        fi
        pause
        ;;
      6)
        [ -x "$CONSOLE_CMD" ] || write_runtime_files
        "$CONSOLE_CMD"
        pause
        ;;
      7) uninstall_vm_service; pause ;;
      0) return ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

uninstall_installer(){
  warn "这只会卸载 routerosinstall 菜单命令本身。RouterOS 虚拟机服务请在菜单 5 中卸载。"
  if confirm "确认删除 $INSTALL_CMD" "n"; then
    rm -f "$INSTALL_CMD"
    ok "routerosinstall 命令已删除。"
    exit 0
  fi
}

menu_exit_or_uninstall(){
  while true; do
    print_title
    printf '%s\n' "1. 退出脚本"
    printf '%s\n' "2. 卸载 routerosinstall 命令"
    printf '%s\n' "0. 返回主菜单"
    printf '%s' "请选择: "
    local choice
    IFS= read -r choice || true
    case "$choice" in
      1) exit 0 ;;
      2) uninstall_installer ;;
      0) return ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

main_menu(){
  need_root
  load_config
  while true; do
    print_title
    printf '%s\n' "1. 依赖安装"
    printf '%s\n' "2. 网络检查"
    printf '%s\n' "3. 虚拟机参数配置"
    printf '%s\n' "4. RouterOS 预设置"
    printf '%s\n' "5. RouterOS 启动/关闭/卸载/开机自启动设置"
    printf '%s\n' "6. 退出脚本/卸载脚本"
    printf '\n%s' "请选择: "
    local choice
    IFS= read -r choice || true
    case "$choice" in
      1) menu_dependencies ;;
      2) menu_network_check ;;
      3) menu_vm_config ;;
      4) menu_routeros_preset ;;
      5) menu_service_manage ;;
      6) menu_exit_or_uninstall ;;
      *) warn "无效选择"; pause ;;
    esac
  done
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  printf '%s\n' "用法:"
  printf '  %s\n' "sudo bash 9.sh            安装 routerosinstall 命令"
  printf '  %s\n' "sudo routerosinstall       打开 RouterOS CHR 安装管理菜单"
  printf '  %s\n' "routeros                   进入 RouterOS 串口控制台"
  exit 0
fi

if [ "${1:-}" = "--run" ]; then
  main_menu
  exit 0
fi

if [ "$(basename "$0")" != "routerosinstall" ]; then
  bootstrap_install
  exit 0
fi

main_menu
